# C++
- id: clang-format
  name: clang-format
  description: Format C/C++ sources with ‹clang-format›.
  entry: clang-format -i
  args:
    - "-style=file"
  language: system
  types_or:
    - c
    - c++

# C#
- id: dotnet-format
  name: dotnet format
  description: Format .NET sources with ‹dotnet format›.
  entry: dotnet-format
  args:
    - "--include"
  language: dotnet
  types_or:
    - c#
    - vb

# Rust
- id: rust-fmt
  name: rustfmt
  description: Format Rust sources with ‹rustfmt›.
  entry: rustfmt
  language: system
  types:
    - rust
- id: rust-clippy
  name: clippy
  description: Lint Rust sources with ‹clippy›.
  entry: rust/clippy-driver.sh
  language: system
  types:
    - rust

# Cargo
- id: cargo-fmt
  name: cargo fmt
  description: Format sources with ‹cargo fmt›.
  entry: cargo fmt
  args:
    - "--"
  language: system
  types:
    - rust
- id: cargo-check
  name: cargo check
  description: Check the crate for errors.
  entry: cargo check
  language: system
  types:
    - rust
  pass_filenames: false
- id: cargo-clippy
  name: cargo clippy
  description: Lint the crate with ‹cargo clippy›.
  entry: cargo clippy
  args:
    - "--"
  language: system
  types:
    - rust
  pass_filenames: false

# Go
- id: gofmt
  name: gofmt
  description: Format Go sources with ‹gofmt›.
  entry: gofmt
  args:
    - "-w"
  language: system
  types:
    - go
