# C++
- id: clang-format
  name: clang-format
  description: Format C/C++ sources with ‹clang-format›.
  entry: clang-format -i
  language: system
  types_or:
    - c
    - c++
  args:
    - "-style=file"

# Rust
- id: rust-fmt
  name: rustfmt
  description: Format Rust sources with ‹rustfmt›.
  entry: rustfmt
  language: system
  types:
    - rust
- id: rust-clippy
  name: clippy
  description: Lint Rust sources with ‹clippy›.
  entry: rust/clippy-driver.sh
  language: system
  types:
    - rust
